### ISSUE TITLE
Adding type annotations to curried functions

### ISSUE THREAD

**Issue by phinate** [dbrattli/FSlash#2]
From what I can see in `core/curry.py`, there's no way to specify type annotations on-the-fly in a meaningful way. However, instead of recommending against usage, is it worth providing a `@functools.wraps` decorator over the called function so some notion of annotation and docstring is preserved?

It trusts that the user knows what they're doing, of course :)

**Comment by dbrattli** [comment]
Thanks for the suggestion. I will try to fix it using `wraps`.
